CoffeeShop/Controllers/OrderController.cs
using CoffeeShop.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using CoffeeShop.BAL;

namespace CoffeeShop.Controllers
{
    [CheckAccess]
    public class OrderController : Controller
    {
        private IConfiguration configuration;

        public OrderController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }
        public static  List<OrderModel> orders = new List<OrderModel>
{
    new OrderModel { OrderID = 1, OrderDate = DateTime.Now, CustomerName = "Alice", PaymentMode = "Credit Card", TotalAmount = 199.99d, ShippingAddress = "123 Main St", UserID = 101 },
    new OrderModel { OrderID = 2, OrderDate = DateTime.Now.AddDays(-1), CustomerName = "Bob", PaymentMode = "PayPal", TotalAmount = 299.99d, ShippingAddress = "124 Main St", UserID = 101 },
    new OrderModel { OrderID = 3, OrderDate = DateTime.Now.AddDays(-2), CustomerName = "Charlie", PaymentMode = "Cash", TotalAmount = 399.99d, ShippingAddress = "125 Main St", UserID = 101 },
    new OrderModel { OrderID = 4, OrderDate = DateTime.Now.AddDays(-3), CustomerName = "David", PaymentMode = null, TotalAmount = 499.99d, ShippingAddress = "126 Main St", UserID = 101 },
    new OrderModel { OrderID = 5, OrderDate = DateTime.Now.AddDays(-4), CustomerName = "Eva", PaymentMode = "Credit Card", TotalAmount = 599.99d, ShippingAddress = "127 Main St", UserID = 101 },
    new OrderModel { OrderID = 6, OrderDate = DateTime.Now.AddDays(-5), CustomerName = "Frank", PaymentMode = "Debit Card", TotalAmount = 699.99d, ShippingAddress = "128 Main St", UserID = 101 },
    new OrderModel { OrderID = 7, OrderDate = DateTime.Now.AddDays(-6), CustomerName = "Grace", PaymentMode = null, TotalAmount = 799.99d, ShippingAddress = "129 Main St", UserID = 101 },
    new OrderModel { OrderID = 8, OrderDate = DateTime.Now.AddDays(-7), CustomerName = "Hank", PaymentMode = "Credit Card", TotalAmount = 899.99d, ShippingAddress = "130 Main St", UserID = 101 },
    new OrderModel { OrderID = 9, OrderDate = DateTime.Now.AddDays(-8), CustomerName = "Ivy", PaymentMode = "PayPal", TotalAmount = 999.99d, ShippingAddress = "131 Main St", UserID = 101 },
    new OrderModel { OrderID = 10, OrderDate = DateTime.Now.AddDays(-9), CustomerName = "Jack", PaymentMode = "Cash", TotalAmount = 1099.99d, ShippingAddress = "132 Main St", UserID = 101 }
};


        #region OrderList
        public IActionResult OrderList()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "SP_SELECT_ALL_ORDER1";
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            return View(table);
            //return View(orders);
        }
        #endregion


        #region AddEditOrder
        public IActionResult AddEditOrder()
        {
            PUserDropDown();
            return View();
        }
        #endregion


        #region OrderEdit
        public IActionResult OrderEdit(int OrderID)
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");

            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = System.Data.CommandType.StoredProcedure;
            command.CommandText = "SP_SELECT_ORDER_BY_ID";
            command.Parameters.Add("@OrderID", SqlDbType.Int).Value = OrderID;
            SqlDataReader reader = command.ExecuteReader();
            DataTable dataTable = new DataTable();
            dataTable.Load(reader);
            connection.Close();

            OrderModel orderModel = new OrderModel();
            orderModel.OrderID = Convert.ToInt32(dataTable.Rows[0]["OrderID"]);
            orderModel.OrderDate = Convert.ToDateTime(dataTable.Rows[0]["OrderDate"]);
            orderModel.CustomerName = dataTable.Rows[0]["CustomerName"].ToString();
            orderModel.PaymentMode = dataTable.Rows[0]["PaymentMode"].ToString();
            orderModel.TotalAmount = Convert.ToDouble(dataTable.Rows[0]["TotalAmount"]);
            orderModel.ShippingAddress = dataTable.Rows[0]["ShippingAddress"].ToString();
            orderModel.UserID = Convert.ToInt32(dataTable.Rows[0]["UserID"]);

            PUserDropDown();
            return View("AddEditOrder", orderModel);
        }
        #endregion


        #region OrderSave
        public IActionResult OrderSave(OrderModel orderModel)
        {

          
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                if (orderModel.OrderID == null)
                {
                    command.CommandText = "SP_INSERT_ORDER";
                }
                else
                {
                    command.CommandText = "SP_UPDATE_ORDER";
                    command.Parameters.Add("@OrderID", SqlDbType.Int).Value = orderModel.OrderID;
                }
                command.Parameters.Add("@OrderDate", SqlDbType.DateTime).Value = orderModel.OrderDate;
                command.Parameters.Add("@CustomerName", SqlDbType.VarChar).Value = orderModel.CustomerName;
                command.Parameters.Add("@PaymentMode", SqlDbType.VarChar).Value = orderModel.PaymentMode;
                command.Parameters.Add("@TotalAmount", SqlDbType.Decimal).Value = orderModel.TotalAmount;
                command.Parameters.Add("@ShippingAddress", SqlDbType.VarChar).Value = orderModel.ShippingAddress;
                command.Parameters.Add("@UserID", SqlDbType.Int).Value = orderModel.UserID;
                command.ExecuteNonQuery();
            TempData["SuccessMessage"] = orderModel.OrderID == null ? "Order added successfully!" : "Order updated successfully!";

            PUserDropDown();
                return RedirectToAction("OrderList");
            }
        #endregion

        #region PUserDropDown

        public void PUserDropDown()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection1 = new SqlConnection(connectionString);
            connection1.Open();
            SqlCommand command1 = connection1.CreateCommand();
            command1.CommandType = System.Data.CommandType.StoredProcedure;
            command1.CommandText = "SP_USER_DROPDOWN";
            SqlDataReader reader1 = command1.ExecuteReader();
            DataTable dataTable1 = new DataTable();
            dataTable1.Load(reader1);
            List<UserDropDownModel> UserList = new List<UserDropDownModel>();
            foreach (DataRow data in dataTable1.Rows)
            {
                UserDropDownModel userDropDownModel = new UserDropDownModel();
               /* userDropDownModel.UserID = Convert.ToInt32(data["UserID"]);*/
                userDropDownModel.UserName = data["UserName"].ToString();
                UserList.Add(userDropDownModel);
            }
            ViewBag.UserList = UserList;
        }
        #endregion

        #region Delete
        public IActionResult Delete(int OrderID)
        {
            try
            {
                string connectionString = configuration.GetConnectionString("ConnectionString");

                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    using (SqlCommand command = connection.CreateCommand())
                    {
                        command.CommandType = CommandType.StoredProcedure;
                        command.CommandText = "SP_DELETE_ORDER";
                        command.Parameters.Add("@OrderID", SqlDbType.Int).Value = OrderID;
                        command.ExecuteNonQuery();
                    }
                }

                return RedirectToAction("OrderList");
            }
            catch (SqlException ex)
            {
                if (ex.Number == 547) // SQL Server error code for foreign key constraint violation
                {
                    TempData["ErrorMessage"] = "Unable to delete the product because it is referenced in another record.";
                }
                else
                {
                    TempData["ErrorMessage"] = "An error occurred while deleting the product. Please try again.";
                }
                Console.WriteLine(ex.ToString());
                return RedirectToAction("OrderList");
            }
            catch (Exception ex)
            {
                TempData["SuccessMessage"] = "Order deleted successfully!";
                Console.WriteLine(ex.ToString());
                return RedirectToAction("OrderList");
            }
        }
        #endregion
    }
}

CoffeeShop/Controllers/UserController.cs
using CoffeeShop.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using CoffeeShop.BAL;

namespace CoffeeShop.Controllers
{
    [CheckAccess]
    public class UserController : Controller
    {
        private IConfiguration configuration;

        public UserController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }
        public static  List<UserModel> users = new List<UserModel>
{
    new UserModel { UserID = 1, UserName = "Alice", Email = "alice@example.com", Password = "password1", MobileNo = "1234567890", Address = "123 Main St", IsActive = true },
    new UserModel { UserID = 2, UserName = "Bob", Email = "bob@example.com", Password = "password2", MobileNo = "1234567891", Address = "124 Main St", IsActive = true },
    new UserModel { UserID = 3, UserName = "Charlie", Email = "charlie@example.com", Password = "password3", MobileNo = "1234567892", Address = "125 Main St", IsActive = true },
    new UserModel { UserID = 4, UserName = "David", Email = "david@example.com", Password = "password4", MobileNo = "1234567893", Address = "126 Main St", IsActive = true },
    new UserModel { UserID = 5, UserName = "Eva", Email = "eva@example.com", Password = "password5", MobileNo = "1234567894", Address = "127 Main St", IsActive = true },
    new UserModel { UserID = 6, UserName = "Frank", Email = "frank@example.com", Password = "password6", MobileNo = "1234567895", Address = "128 Main St", IsActive = true },
    new UserModel { UserID = 7, UserName = "Grace", Email = "grace@example.com", Password = "password7", MobileNo = "1234567896", Address = "129 Main St", IsActive = true },
    new UserModel { UserID = 8, UserName = "Hank", Email = "hank@example.com", Password = "password8", MobileNo = "1234567897", Address = "130 Main St", IsActive = true },
    new UserModel { UserID = 9, UserName = "Ivy", Email = "ivy@example.com", Password = "password9", MobileNo = "1234567898", Address = "131 Main St", IsActive = true },
    new UserModel { UserID = 10, UserName = "Jack", Email = "jack@example.com", Password = "password10", MobileNo = "1234567899", Address = "132 Main St", IsActive = true }
};

        #region UserList
        public IActionResult UserList()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "SP_SELECT_ALL_User ";
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            return View(table);
            //return View(users);
        }
        #endregion

        #region AddEditUser
        public IActionResult AddEditUser()
        {
            return View();
        }
        #endregion


        #region UserSave
        [HttpPost]
        public IActionResult UserSave(UserModel user)
        {
            
                    string connectionString = this.configuration.GetConnectionString("ConnectionString");
                    using (SqlConnection connection = new SqlConnection(connectionString))
                    {
                        connection.Open();
                        using (SqlCommand command = connection.CreateCommand())
                        {
                            command.CommandType = CommandType.StoredProcedure;

                            if (user.UserID == null)
                            {
                                command.CommandText = "SP_INSERT_USER";
                            }
                            else
                            {
                                command.CommandText = "SP_UPDATE_USER";
                                command.Parameters.Add("@UserID", SqlDbType.Int).Value = user.UserID;
                            }

                            command.Parameters.Add("@UserName", SqlDbType.VarChar).Value = user.UserName;
                            command.Parameters.Add("@Email", SqlDbType.VarChar).Value = user.Email;
                            command.Parameters.Add("@Password", SqlDbType.VarChar).Value = user.Password;
                            command.Parameters.Add("@MobileNo", SqlDbType.VarChar).Value = user.MobileNo;
                            command.Parameters.Add("@Address", SqlDbType.VarChar).Value = user.Address;
                            command.Parameters.Add("@IsActive", SqlDbType.Bit).Value = user.IsActive;
                            command.ExecuteNonQuery();
                        }
                    }
            TempData["SuccessMessage"] = user.UserID == null ? "User added successfully!" : "User updated successfully!";
            return RedirectToAction("UserList");
           
        }
        #endregion


        #region UserEdit
        public IActionResult UserEdit(int UserID)
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");

            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = System.Data.CommandType.StoredProcedure;
            command.CommandText = "SP_SELECT_USER_BY_ID";
            command.Parameters.Add("@UserID", SqlDbType.Int).Value = UserID;
            SqlDataReader reader = command.ExecuteReader();
            DataTable dataTable = new DataTable();
            dataTable.Load(reader);
            connection.Close();

            UserModel UserModel = new UserModel();
            UserModel.UserID = Convert.ToInt32(dataTable.Rows[0]["UserID"]);
            UserModel.UserName = dataTable.Rows[0]["UserName"].ToString();
            UserModel.Email = dataTable.Rows[0]["Email"].ToString();
            UserModel.Password = dataTable.Rows[0]["Password"].ToString();
            UserModel.MobileNo = dataTable.Rows[0]["MobileNo"].ToString();
            UserModel.Address = dataTable.Rows[0]["Address"].ToString();
            UserModel.IsActive = Convert.ToBoolean(dataTable.Rows[0]["IsActive"]);

            return View("AddEditUser", UserModel);
        }
        #endregion


        #region Delete
        public IActionResult Delete(int UserID)
        {
            try
            {
                string connectionString = configuration.GetConnectionString("ConnectionString");

                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    using (SqlCommand command = connection.CreateCommand())
                    {
                        command.CommandType = CommandType.StoredProcedure;
                        command.CommandText = "SP_DELETE_USER";
                        command.Parameters.Add("@UserID", SqlDbType.Int).Value = UserID;
                        command.ExecuteNonQuery();
                    }
                }

                return RedirectToAction("UserList");
            }
            catch (SqlException ex)
            {
                if (ex.Number == 547) // SQL Server error code for foreign key constraint violation
                {
                    TempData["ErrorMessage"] = "Unable to delete the product because it is referenced in another record.";
                }
                else
                {
                    TempData["ErrorMessage"] = "An error occurred while deleting the product. Please try again.";
                }
                Console.WriteLine(ex.ToString());
                return RedirectToAction("UserList");
            }
            catch (Exception ex)
            {
                TempData["SuccessMessage"] = "User deleted successfully!";
                Console.WriteLine(ex.ToString());
                return RedirectToAction("UserList");
            }
        }

        #endregion
    }
}

CoffeeShop/Views/Shared/Error404.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>404 - Page Not Found</title>
   
   <style>
        body {
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
         /*    background-color: #f2f2f2; */
           background-color:antiquewhite;
            color: #333;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            text-align: center;
        }

        .error-code {
            font-size: 10rem;
            margin: 0;
            color: #e74c3c;
        }

        .error-message {
            font-size: 1.5rem;
            margin: 0;
            margin-bottom: 20px;
        }

        .home-link {
            text-decoration: none;
            color: #3498db;
            font-size: 1.2rem;
            border: 1px solid #3498db;
            padding: 10px 20px;
            border-radius: 5px;
            transition: background-color 0.3s, color 0.3s;
        }

            .home-link:hover {
                background-color: #3498db;
                color: white;
            }

   </style>
</head>
<body>
    <div class="container">
        <h1 class="error-code">404</h1>
        <p class="error-message">Oops! The page you're looking for doesn't exist.</p>
        <a class="btn btn-outline-info" href="/" class="home-link">Go back to Home</a>
    </div>
</body>
</html>

CoffeeShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoffeeShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CoffeeShop.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />


   @*  Sweet Alert..! *@
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm  navbar navbar-light bg-light  border-bottom box-shadow mb-3">
            <div class="container-fluid">
@* 
                <a class="navbar-brand" asp-controller="Home" asp-action="Index" style="font-family: cursive; font-size: 20px;">
                    <img src="~/image/logo.jpg" width="30" height="30" class="d-inline-block align-top" alt="">
                    CoffeeShop
                </a> *@
                <a class="navbar-brand" asp-controller="Home" asp-action="Index" style="font-family: cursive; font-size: 20px;">
                  <i class="fas fa-coffee" style="margin-right: 5px;"></i>
                      CoffeeShop
                </a>

               
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item " style="font-family: serif; font-size: 20px;">
                            <a class="nav-link text-dark"  asp-area="" asp-controller="Home" asp-action="HomePage">Home</a>
                        </li>
                        <li class="nav-item" style="font-family: serif; font-size:20px;">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="ProductList">Product</a>
                        </li>
                        <li class="nav-item" style="font-family: serif; font-size:20px;">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="UserList">User</a>
                        </li>
                        <li class="nav-item" style="font-family: serif; font-size:20px;">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="OrderList">
                               Order
                            </a>
                        </li>
                        <li class="nav-item" style="font-family: serif; font-size:20px;">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OrderDetails" asp-action="OrderDetailList">OrderDetails</a>
                        </li>
                        <li class="nav-item" style="font-family: serif; font-size:20px;">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bills" asp-action="BillsList">Bills</a>
                        </li>

                        
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <form asp-area="" asp-controller="Home" asp-action="Logout" method="post" class="form-inline" style="font-family: cursive; font-size: 20px;">
                                <button type="submit" class="text-dark btn btn-outline-success">
                                    Logout
                                    <i class="fas fa-sign-out-alt" style="margin-right: 5px;"></i>
                                  
                                </button>
                            </form>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CoffeeShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
     <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script> 

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CoffeeShop/Views/Shared/_Layout_Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoffeeShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CoffeeShop.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />


    @*  Sweet Alert..! *@

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
   
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>