CoffeeShop/Controllers/OrderDetailsController.cs
using CoffeeShop.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using CoffeeShop.BAL;

namespace CoffeeShop.Controllers
{
    [CheckAccess]
    public class OrderDetailsController : Controller
    {

        private IConfiguration configuration;

        public OrderDetailsController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }
        public static  List<OrderDetailsModel> orderDetails = new List<OrderDetailsModel>
{
    new OrderDetailsModel { OrderDetailID = 1, OrderID = 1, ProductID = 1, Quantity = 2, Amount = 19.99d, TotalAmount = 39.98d, UserID = 101 },
    new OrderDetailsModel { OrderDetailID = 2, OrderID = 2, ProductID = 2, Quantity = 1, Amount = 29.99d, TotalAmount = 29.99d, UserID = 101 },
    new OrderDetailsModel { OrderDetailID = 3, OrderID = 3, ProductID = 3, Quantity = 3, Amount = 39.99d, TotalAmount = 119.9d, UserID = 101 },
    new OrderDetailsModel { OrderDetailID = 4, OrderID = 4, ProductID = 4, Quantity = 4, Amount = 49.99d, TotalAmount = 199.96d, UserID = 101 },
    new OrderDetailsModel { OrderDetailID = 5, OrderID = 5, ProductID = 5, Quantity = 2, Amount = 59.99d, TotalAmount = 119.98d, UserID = 101 },
    new OrderDetailsModel { OrderDetailID = 6, OrderID = 6, ProductID = 6, Quantity = 1, Amount = 69.99d, TotalAmount = 69.99d, UserID = 101 },
    new OrderDetailsModel { OrderDetailID = 7, OrderID = 7, ProductID = 7, Quantity = 3, Amount = 79.99d, TotalAmount = 239.97d, UserID = 101 },
    new OrderDetailsModel { OrderDetailID = 8, OrderID = 8, ProductID = 8, Quantity = 2, Amount = 89.99d, TotalAmount = 179.98d, UserID = 101 },
    new OrderDetailsModel { OrderDetailID = 9, OrderID = 9, ProductID = 9, Quantity = 1, Amount = 99.99d, TotalAmount = 99.99d, UserID = 101 },
    new OrderDetailsModel { OrderDetailID = 10, OrderID = 10, ProductID = 10, Quantity = 4, Amount = 109.99d, TotalAmount = 439.96d, UserID = 101 }
};


        #region OrderDetailList
        public IActionResult OrderDetailList()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "SP_SELECT_ALL_ORDERDETAILS ";
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            return View(table);
            //return View(orderDetails);
        }
        #endregion

        #region AddEditOrderDetails
        public IActionResult AddEditOrderDetails()
        {
            ProductDropDown();
            PUserDropDown();
            OrderDropDown();
            return View();
        }
        #endregion

        #region OrderDetailsEdit

        public IActionResult OrderDetailsEdit(int OrderDetailID)
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");

            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = System.Data.CommandType.StoredProcedure;
            command.CommandText = "SP_SELECT_ORDERDETAILS_BY_ID";
            command.Parameters.Add("@OrderDetailID", SqlDbType.Int).Value = OrderDetailID;
            SqlDataReader reader = command.ExecuteReader();
            DataTable dataTable = new DataTable();
            dataTable.Load(reader);
            connection.Close();

            OrderDetailsModel orderDetailsModel = new OrderDetailsModel();
            orderDetailsModel.OrderDetailID = Convert.ToInt32(dataTable.Rows[0]["OrderDetailID"]);
            orderDetailsModel.OrderID = Convert.ToInt32(dataTable.Rows[0]["OrderID"]);
            orderDetailsModel.ProductID = Convert.ToInt32(dataTable.Rows[0]["ProductID"]);
            orderDetailsModel.Quantity = Convert.ToInt32(dataTable.Rows[0]["Quantity"]);
            orderDetailsModel.Amount = Convert.ToDouble(dataTable.Rows[0]["Amount"]);
            orderDetailsModel.TotalAmount = Convert.ToDouble(dataTable.Rows[0]["TotalAmount"]);
            orderDetailsModel.UserID = Convert.ToInt32(dataTable.Rows[0]["UserID"]);
            ProductDropDown();
            PUserDropDown();
            OrderDropDown();
            return View("AddEditOrderDetails", orderDetailsModel);
        }
        #endregion

        #region PUserDropDown
        public void PUserDropDown()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection1 = new SqlConnection(connectionString);
            connection1.Open();
            SqlCommand command1 = connection1.CreateCommand();
            command1.CommandType = System.Data.CommandType.StoredProcedure;
            command1.CommandText = "SP_USER_DROPDOWN";
            SqlDataReader reader1 = command1.ExecuteReader();
            DataTable dataTable1 = new DataTable();
            dataTable1.Load(reader1);
            List<UserDropDownModel> UserList = new List<UserDropDownModel>();
            foreach (DataRow data in dataTable1.Rows)
            {
                UserDropDownModel userDropDownModel = new UserDropDownModel();
                userDropDownModel.UserID = Convert.ToInt32(data["UserID"]);
                userDropDownModel.UserName = data["UserName"].ToString();
                UserList.Add(userDropDownModel);
            }
            ViewBag.UserList = UserList;
        }
        #endregion

        #region OrderDropDown
        public void OrderDropDown()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection1 = new SqlConnection(connectionString);
            connection1.Open();
            SqlCommand command1 = connection1.CreateCommand();
            command1.CommandType = System.Data.CommandType.StoredProcedure;
            command1.CommandText = "SP_ORDER_DROPDOWN";
            SqlDataReader reader1 = command1.ExecuteReader();
            DataTable dataTable1 = new DataTable();
            dataTable1.Load(reader1);
            List<OrderDropDownModel> OrderList = new List<OrderDropDownModel>();
            foreach (DataRow data in dataTable1.Rows)
            {
                OrderDropDownModel orderDropDownModel = new OrderDropDownModel();
                orderDropDownModel.OrderID = Convert.ToInt32(data["OrderID"]);
                orderDropDownModel.CustomerName = data["CustomerName"].ToString();
                OrderList.Add(orderDropDownModel);
            }
            ViewBag.OrderList = OrderList;
        }
        #endregion


        #region ProductDropDown
        public void ProductDropDown()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection1 = new SqlConnection(connectionString);
            connection1.Open();
            SqlCommand command1 = connection1.CreateCommand();
            command1.CommandType = System.Data.CommandType.StoredProcedure;
            command1.CommandText = "SP_PRODUCT_DROPDOWN";
            SqlDataReader reader1 = command1.ExecuteReader();
            DataTable dataTable1 = new DataTable();
            dataTable1.Load(reader1);
            List<ProductDropDownModel> ProductList = new List<ProductDropDownModel>();
            foreach (DataRow data in dataTable1.Rows)
            {
                ProductDropDownModel productDropDownModel = new ProductDropDownModel();
                productDropDownModel.ProductID = Convert.ToInt32(data["ProductID"]);
                productDropDownModel.ProductName = data["ProductName"].ToString();
                ProductList.Add(productDropDownModel);
            }
            ViewBag.ProductList = ProductList;
        }
        #endregion


        #region Save
        public IActionResult Save(OrderDetailsModel orderDetailsModel)
        {
           
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                if (orderDetailsModel.OrderDetailID == null)
                {
                    command.CommandText = "SP_INSERT_ORDERDETAILS";
                }
                else
                {
                    command.CommandText = "SP_UPDATE_ORDERDETAILS";
                    command.Parameters.Add("@OrderDetailID", SqlDbType.Int).Value = orderDetailsModel.OrderDetailID;
                }
                command.Parameters.Add("@OrderID", SqlDbType.VarChar).Value = orderDetailsModel.OrderID;
                command.Parameters.Add("@ProductID", SqlDbType.VarChar).Value = orderDetailsModel.ProductID;
                command.Parameters.Add("@Quantity", SqlDbType.VarChar).Value = orderDetailsModel.Quantity;
                command.Parameters.Add("@Amount", SqlDbType.VarChar).Value = orderDetailsModel.Amount;
                command.Parameters.Add("@TotalAmount", SqlDbType.VarChar).Value = orderDetailsModel.TotalAmount;
                command.Parameters.Add("@UserID", SqlDbType.VarChar).Value = orderDetailsModel.UserID;
                command.ExecuteNonQuery();
                TempData["SuccessMessage"] = orderDetailsModel.OrderDetailID == null ? "OrderDetail added successfully!" : "OrderDetail updated successfully!";

                ProductDropDown();
                PUserDropDown();
                 OrderDropDown();
                return RedirectToAction("OrderDetailList");
            

CoffeeShop/Views/OrderDetails/AddEditOrderDetails.cshtml
@model OrderDetailsModel;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Order Details</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <style>
        .form-container {
            max-width: 600px;
            margin: auto;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 8px;
        }

        .form-label {
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="card-body form-container">
        <h1 class="card-title text-center">Add Order Details</h1>
        <!-- Vertical Form -->
        <form class="row g-3 needs-validation" id="orderDetailsForm" asp-action="Save" method="post" >
           <input type="hidden" asp-for="OrderDetailID" />
            <div class="col-12">
                <label for="inputUserId" class="form-label">Customer Name</label>
                <select class="form-control" asp-for="OrderID">
                    <option value="">Select Customer</option>
                    @foreach (var user in ViewBag.OrderList)
                    {
                        <option value="@user.OrderID">@user.CustomerName</option>
                    }
                </select>
                <span class="text text-danger" asp-validation-for="OrderID"></span>
            </div>




            <div class="col-12">
                <label for="inputUserId" class="form-label">Product Name</label>
                <select class="form-control" asp-for="ProductID">
                    <option value="">Select Product</option>
                    @foreach (var user in ViewBag.ProductList)
                    {
                        <option value="@user.ProductID">@user.ProductName</option>
                    }
                </select>
                <span class="text text-danger" asp-validation-for="ProductID"></span>
            </div>

           

            <div class="col-12">
                <label for="inputQuantity" class="form-label fw-black fs-5">Quantity</label>
                <input type="number" class="form-control" id="inputQuantity" name="Quantity" asp-for="Quantity" placeholder="Quantity" oninput="calculateTotalAmount()">
                <span class="text-danger" asp-validation-for="Quantity"></span>
            </div>

            <div class="col-12">
                <label for="inputAmount" class="form-label fw-black fs-5">Amount</label>
                <input type="number" class="form-control" id="inputAmount" name="Amount" asp-for="Amount" placeholder="Amount" oninput="calculateTotalAmount()">
                <span class="text-danger" asp-validation-for="Amount"></span>
            </div>

            <div class="col-12">
                <label for="inputTotalAmount" class="form-label fw-black fs-5">Total Amount</label>
                <input type="number" class="form-control" id="inputTotalAmount" name="TotalAmount" asp-for="TotalAmount" placeholder="Total Amount" readonly>
                <span class="text-danger" asp-validation-for="TotalAmount"></span>
            </div>

            <script>
                function calculateTotalAmount() {
                    const quantity = parseFloat(document.getElementById('inputQuantity').value) || 0;
                    const amount = parseFloat(document.getElementById('inputAmount').value) || 0;
                    const totalAmount = quantity * amount;
                    document.getElementById('inputTotalAmount').value = totalAmount.toFixed(2); // Update total amount
                }
            </script>


            <div class="col-12">
                <label for="inputUserId" class="form-label">User Name</label>
                <select class="form-control" asp-for="UserID">
                    <option value="">Select User</option>
                    @foreach (var user in ViewBag.UserList)
                    {
                        <option value="@user.UserID">@user.UserName</option>
                    }
                </select>
                <span class="text text-danger" asp-validation-for="UserID"></span>
            </div>



            <div class="text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a asp-action="OrderDetailList" asp-controller="OrderDetails" class="btn btn-secondary">Cancel </a>
            </div>
        </form>
    </div>

   
</body>
</html>

CoffeeShop/Views/OrderDetails/OrderDetailList.cshtml
@* @model List<CoffeeShop.Models.OrderDetailsModel>
 *@

 @using System.Data;
@model DataTable;

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["ErrorMessage"]
    </div>
}

@if (TempData["SuccessMessage"] != null)
{
    <script>
        Swal.fire({
            icon: 'success',
            title: '@TempData["SuccessMessage"]',
            showConfirmButton: false,
            timer: 2500
        });
    </script>
}



<h1 align="center"><b>OrderDetail List</b></h1>
<a asp-action="AddEditOrderDetails" asp-controller="OrderDetails">
    <button class="btn btn-primary">Add Order Detail</button>

</a>
<table class="table table-striped">
    <thead>
        <tr>
          @*   <th scope="col">OrderDetailID</th> *@
            <th scope="col">CustomerName </th>
            <th scope="col">ProductName </th>
            <th scope="col">Quantity </th>
            <th scope="col">Amount </th>
            <th scope="col">Total Amount</th>
            <th scope="col">UserName</th>
            <th>Action</th>
            
        </tr>
    </thead>
    <tbody>
         @if(Model.Rows.Count > 0){
             foreach (DataRow o in Model.Rows)
        {
            <tr>
                @* <td scope="col">@o["OrderDetailID"]</td> *@
                <td scope="col">@o["CustomerName"]</td>
                <td scope="col">@o["ProductName"]</td>
                <td scope="col">@o["Quantity"]</td>
                <td scope="col">@o["Amount"]</td>
                <th scope="col">@o["TotalAmount"] </th>
                <td scope="col">@o["UserName"]</td>
                <td>
                        <a asp-action="OrderDetailsEdit" asp-controller="OrderDetails" asp-route-OrderDetailID="@o["OrderDetailID"]" class="btn btn-success">
                            <i class="fa-solid fa-pen-to-square"></i>
                        </a>

                        <a href="javascript:void(0);" class="btn btn-danger" onclick="deleteOrderDetail('@o["OrderDetailID"]')">
                            <i class="fa-solid fa-trash"></i>
                        </a>
                </td>


            </tr>
        }
         }
        
    </tbody>
</table>

<script type="text/javascript">
    function deleteOrderDetail(orderdetailId) {
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = '/OrderDetails/Delete?OrderDetailID=' + orderdetailId;
            }
        });
    }
</script>